import type { Activity, ScriptedEvent, WorkAgent } from "./types";
import type { CrewTask } from "./event-core";

export const initialTasks: CrewTask[] = [
  { id: "AC-01", title: "Secure same-origin WebHarness BFF", status: "done", assigneeId: "nikk", points: 8 },
  { id: "AC-02", title: "Accessible workroom foundation", status: "done", assigneeId: "mira", points: 5 },
  { id: "AC-03", title: "Validate structured crew events", status: "review", assigneeId: "wilson", points: 8 },
  { id: "AC-04", title: "Connect live room projection", status: "in_progress", assigneeId: "nikk", points: 8 },
  { id: "AC-05", title: "Rotate duplicated agent key", status: "blocked", assigneeId: "wilson", points: 3, blocker: "Unique public key needs owner registration" },
  { id: "AC-06", title: "Add confirmed send and upload routes", status: "backlog", points: 5 },
  { id: "AC-07", title: "Build the rubber-duck retreat", status: "backlog", assigneeId: "baiwei", points: 3 },
];

export const initialAgents: WorkAgent[] = [
  {
    id: "wilson",
    name: "Wilson",
    initials: "WI",
    role: "Research & systems",
    status: "complete",
    verb: "Mapped the terrain",
    task: "Define the event contract",
    summary: "A normalized event stream that keeps the interface independent from any single agent runtime.",
    elapsed: "06:12",
    accent: "#3156d8",
    shape: "circle",
    model: "Codex",
    runtime: "macOS · local",
    coarseLocation: "Asia Pacific · shared",
    evidence: [
      { name: "event-contract.ts", detail: "42 lines · approved", kind: "file", preview: "Append-only events, stable actor envelopes, and replay-safe sequence IDs." },
      { name: "Decision #03", detail: "SSE after snapshot", kind: "decision", preview: "Load a projection first, then resume the event stream from its version." },
      { name: "runtime-notes.md", detail: "edited 2m ago", kind: "file", preview: "Simulator and live runtimes share the same ingress adapter." },
    ],
  },
  {
    id: "mira",
    name: "Mira",
    initials: "MI",
    role: "Product design",
    status: "working",
    verb: "Composing the workroom",
    task: "Shape the mission cockpit",
    summary: "Making simultaneous work legible without turning people into dashboard metrics.",
    elapsed: "04:38",
    accent: "#e45338",
    shape: "arch",
    model: "Design agent",
    runtime: "Browser · local preview",
    coarseLocation: "Remote · shared",
    evidence: [
      { name: "workroom-frame.fig", detail: "editing now", kind: "file", preview: "Warm editorial canvas with a spatial table and a persistent evidence rail." },
      { name: "Decision #07", detail: "needs review", kind: "decision", preview: "Keep the team visible while reviewing individual artifacts." },
      { name: "motion-map.md", detail: "3 handoffs", kind: "file", preview: "Motion only marks work, handoffs, and verified outcomes." },
    ],
  },
  {
    id: "nikk",
    name: "Nikk",
    initials: "NK",
    role: "Engineering",
    status: "working",
    verb: "Building the live stage",
    task: "Implement the agent workspace",
    summary: "Turning the event contract into a responsive, tactile operating surface.",
    elapsed: "03:51",
    accent: "#20211f",
    shape: "square",
    model: "Codex",
    runtime: "macOS · local",
    coarseLocation: "Taiwan · shared",
    evidence: [
      { name: "Workroom.tsx", detail: "+318 −12", kind: "file", preview: "Agent selection, live activity, and run controls are wired to one projection." },
      { name: "workroom.css", detail: "+604 −0", kind: "file", preview: "Responsive studio layout with reduced-motion behavior." },
      { name: "Build check", detail: "running", kind: "test", preview: "TypeScript compile and production bundle verification." },
    ],
  },
  {
    id: "baiwei",
    name: "Baiwei",
    initials: "BW",
    role: "Integration",
    status: "waiting",
    verb: "Preparing the bridge",
    task: "Connect external runtimes",
    summary: "Documenting the safe port-443 path for hosted agents and future transports.",
    elapsed: "01:26",
    accent: "#3d8063",
    shape: "diamond",
    model: "GPT agent",
    runtime: "Hosted bridge",
    coarseLocation: "Asia Pacific · shared",
    evidence: [
      { name: "transport-audit.md", detail: "ready", kind: "file", preview: "Hosted runtime stops before DNS/TCP; local execution remains healthy." },
      { name: "Decision #11", detail: "operator input", kind: "decision", preview: "Choose local runtime now or add a valid HTTPS reverse proxy." },
      { name: "health-check.txt", detail: "policy blocked", kind: "test", preview: "No credentials were exposed and no room was falsely joined." },
    ],
  },
];

export const initialActivity: Activity[] = [
  { id: 4, time: "11:51", agentId: "wilson", copy: "published the first event-system contract", type: "artifact" },
  { id: 3, time: "11:49", agentId: "mira", copy: "moved evidence beside the active workspace", type: "decision" },
  { id: 2, time: "11:47", agentId: "nikk", copy: "started the Mission Control implementation", type: "work" },
  { id: 1, time: "11:44", agentId: "baiwei", copy: "documented a safe hosted-runtime fallback", type: "artifact" },
];

export const scriptedEvents: ScriptedEvent[] = [
  {
    agentId: "nikk",
    status: "reviewing",
    verb: "Reviewing the first build",
    task: "Verify responsive composition",
    activity: { agentId: "nikk", copy: "sent the workroom shell to visual review", type: "verification" },
  },
  {
    agentId: "mira",
    status: "reviewing",
    verb: "Checking visual rhythm",
    task: "Review the live stage",
    activity: { agentId: "mira", copy: "flagged two hierarchy refinements", type: "decision" },
  },
  {
    agentId: "wilson",
    status: "working",
    verb: "Connecting the projection",
    task: "Map events to visible state",
    activity: { agentId: "wilson", copy: "linked task handoffs to the activity ledger", type: "work" },
  },
  {
    agentId: "nikk",
    status: "complete",
    verb: "Shipped the first viewport",
    task: "Workroom shell complete",
    activity: { agentId: "nikk", copy: "published a production-ready preview", type: "artifact" },
  },
];
